
MC.TIMING = {
    CAST_FINISH_THRESHOLD = 0.75,
    GCD_REMAINING_THRESHOLD = 0.75,
    GCD_BUFFER = 1.5,
    GCD_BUFFER_FIREBLAST = 1.5,
    ARCANE_RUPTURE_MIN_DURATION = 2
}

MC.DEFAULT_ACTIONBAR_SLOT = {
    FIREBLAST = 1,
    ARCANE_RUPTURE = 2,
    ARCANE_SURGE = 5
}

MC.GLOBAL_COOLDOWN_IN_SECONDS = 1.5

MC.HASTE = {
    HASTE_THRESHOLD = 30,
    BASE_VALUE = 10
}